//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET_API.Configuracoes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Config())));
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strConnection {
            get {
                return ((string)(this["strConnection"]));
            }
            set {
                this["strConnection"] = value;
            }
        }
        public static Config Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_IDBanco {
            get {
                return ((int)(this["G_IDBanco"]));
            }
            set {
                this["G_IDBanco"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lemon")]
        public string G_Sistema
        {
            get
            {
                return ((string)(this["G_Sistema"]));
            }
            set
            {
                this["G_Sistema"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Usuario_Nome
        {
            get
            {
                return ((string)(this["G_Usuario_Nome"]));
            }
            set
            {
                this["G_Usuario_Nome"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Usuario
        {
            get
            {
                return ((string)(this["G_Usuario"]));
            }
            set
            {
                this["G_Usuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Empresa_Cod
        {
            get
            {
                return ((int)(this["G_Empresa_Cod"]));
            }
            set
            {
                this["G_Empresa_Cod"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Senha
        {
            get
            {
                return ((string)(this["G_Senha"]));
            }
            set
            {
                this["G_Senha"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_SolicitarImpressora
        {
            get
            {
                return ((bool)(this["G_SolicitarImpressora"]));
            }
            set
            {
                this["G_SolicitarImpressora"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_LocalBancoDados
        {
            get
            {
                return ((string)(this["G_LocalBancoDados"]));
            }
            set
            {
                this["G_LocalBancoDados"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Usuario_ChUn_Codigo
        {
            get
            {
                return ((int)(this["G_Usuario_ChUn_Codigo"]));
            }
            set
            {
                this["G_Usuario_ChUn_Codigo"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Usuario_GrupoUsuario
        {
            get
            {
                return ((string)(this["G_Usuario_GrupoUsuario"]));
            }
            set
            {
                this["G_Usuario_GrupoUsuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Empresa_Nome
        {
            get
            {
                return ((string)(this["G_Empresa_Nome"]));
            }
            set
            {
                this["G_Empresa_Nome"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Usuario_Administrador
        {
            get
            {
                return ((string)(this["G_Usuario_Administrador"]));
            }
            set
            {
                this["G_Usuario_Administrador"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_BancoDadosCod
        {
            get
            {
                return ((int)(this["G_BancoDadosCod"]));
            }
            set
            {
                this["G_BancoDadosCod"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_SistemaCpuCod
        {
            get
            {
                return ((string)(this["G_SistemaCpuCod"]));
            }
            set
            {
                this["G_SistemaCpuCod"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Ma_IdUsuario_codCliente
        {
            get
            {
                return ((int)(this["G_Ma_IdUsuario_codCliente"]));
            }
            set
            {
                this["G_Ma_IdUsuario_codCliente"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Sistema_pasta
        {
            get
            {
                return ((string)(this["G_Sistema_pasta"]));
            }
            set
            {
                this["G_Sistema_pasta"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string G_Rebanho
        {
            get
            {
                return ((string)(this["G_Rebanho"]));
            }
            set
            {
                this["G_Rebanho"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string G_LitEquinos
        {
            get
            {
                return ((string)(this["G_LitEquinos"]));
            }
            set
            {
                this["G_LitEquinos"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_AbertoPeloComando
        {
            get
            {
                return ((bool)(this["G_AbertoPeloComando"]));
            }
            set
            {
                this["G_AbertoPeloComando"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_PerguntaFecharAplicacao
        {
            get
            {
                return ((bool)(this["G_PerguntaFecharAplicacao"]));
            }
            set
            {
                this["G_PerguntaFecharAplicacao"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDadosStringConection
        {
            get
            {
                return ((string)(this["G_BancoDadosStringConection"]));
            }
            set
            {
                this["G_BancoDadosStringConection"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDadosCatalog
        {
            get
            {
                return ((string)(this["G_BancoDadosCatalog"]));
            }
            set
            {
                this["G_BancoDadosCatalog"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDadosUID
        {
            get
            {
                return ((string)(this["G_BancoDadosUID"]));
            }
            set
            {
                this["G_BancoDadosUID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDadosPWD
        {
            get
            {
                return ((string)(this["G_BancoDadosPWD"]));
            }
            set
            {
                this["G_BancoDadosPWD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_Certificadora_Nome
        {
            get
            {
                return ((string)(this["G_Certificadora_Nome"]));
            }
            set
            {
                this["G_Certificadora_Nome"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Certificadora_cod_Sucesso
        {
            get
            {
                return ((int)(this["G_Certificadora_cod_Sucesso"]));
            }
            set
            {
                this["G_Certificadora_cod_Sucesso"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Certificadora_cod_erro
        {
            get
            {
                return ((int)(this["G_Certificadora_cod_erro"]));
            }
            set
            {
                this["G_Certificadora_cod_erro"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Certificadora_cod_loginInvalido
        {
            get
            {
                return ((int)(this["G_Certificadora_cod_loginInvalido"]));
            }
            set
            {
                this["G_Certificadora_cod_loginInvalido"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_Certificadora_cod_DadosInvalidos
        {
            get
            {
                return ((int)(this["G_Certificadora_cod_DadosInvalidos"]));
            }
            set
            {
                this["G_Certificadora_cod_DadosInvalidos"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_SistemaPLacaMaeSerial
        {
            get
            {
                return ((string)(this["G_SistemaPLacaMaeSerial"]));
            }
            set
            {
                this["G_SistemaPLacaMaeSerial"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool G_Certificadora_webservice_teste
        {
            get
            {
                return ((bool)(this["G_Certificadora_webservice_teste"]));
            }
            set
            {
                this["G_Certificadora_webservice_teste"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int G_SisbovQtdDigts
        {
            get
            {
                return ((int)(this["G_SisbovQtdDigts"]));
            }
            set
            {
                this["G_SisbovQtdDigts"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_SistemaNomeMaquina
        {
            get
            {
                return ((string)(this["G_SistemaNomeMaquina"]));
            }
            set
            {
                this["G_SistemaNomeMaquina"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_SistemaServidor
        {
            get
            {
                return ((bool)(this["G_SistemaServidor"]));
            }
            set
            {
                this["G_SistemaServidor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_SistemaServidorClienteName
        {
            get
            {
                return ((string)(this["G_SistemaServidorClienteName"]));
            }
            set
            {
                this["G_SistemaServidorClienteName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Embrião")]
        public string G_Embriao
        {
            get
            {
                return ((string)(this["G_Embriao"]));
            }
            set
            {
                this["G_Embriao"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000\'.\'000\'.\'000\'-\'00")]
        public string Format_CPF
        {
            get
            {
                return ((string)(this["Format_CPF"]));
            }
            set
            {
                this["Format_CPF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00\'.\'000\'.\'000\'/\'0000\'-\'00")]
        public string Format_CNPJ
        {
            get
            {
                return ((string)(this["Format_CNPJ"]));
            }
            set
            {
                this["Format_CNPJ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000\'.\'00000\'.\'00\'-\'0")]
        public string Format_PIS
        {
            get
            {
                return ((string)(this["Format_PIS"]));
            }
            set
            {
                this["Format_PIS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0\'.\'000\'.\'000\'-\'0")]
        public string Formar_NIRF
        {
            get
            {
                return ((string)(this["Formar_NIRF"]));
            }
            set
            {
                this["Formar_NIRF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000\'.\'000\'.\'000\'.\'000\'-\'0")]
        public string Format_INCRA
        {
            get
            {
                return ((string)(this["Format_INCRA"]));
            }
            set
            {
                this["Format_INCRA"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/17/2017 12:06:00")]
        public global::System.DateTime G_DataAtualizador
        {
            get
            {
                return ((global::System.DateTime)(this["G_DataAtualizador"]));
            }
            set
            {
                this["G_DataAtualizador"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Boletos\\")]
        public string G_BoletoFolder
        {
            get
            {
                return ((string)(this["G_BoletoFolder"]));
            }
            set
            {
                this["G_BoletoFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_CaminhoArquivosDLL
        {
            get
            {
                return ((string)(this["G_CaminhoArquivosDLL"]));
            }
            set
            {
                this["G_CaminhoArquivosDLL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_NFeConfigInicializada
        {
            get
            {
                return ((bool)(this["G_NFeConfigInicializada"]));
            }
            set
            {
                this["G_NFeConfigInicializada"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_CultureName
        {
            get
            {
                return ((string)(this["G_CultureName"]));
            }
            set
            {
                this["G_CultureName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_CultureDisplayName
        {
            get
            {
                return ((string)(this["G_CultureDisplayName"]));
            }
            set
            {
                this["G_CultureDisplayName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_OSFullName
        {
            get
            {
                return ((string)(this["G_OSFullName"]));
            }
            set
            {
                this["G_OSFullName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_OSPlatForm
        {
            get
            {
                return ((string)(this["G_OSPlatForm"]));
            }
            set
            {
                this["G_OSPlatForm"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_OSVersion
        {
            get
            {
                return ((string)(this["G_OSVersion"]));
            }
            set
            {
                this["G_OSVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_FrameworkVersion
        {
            get
            {
                return ((string)(this["G_FrameworkVersion"]));
            }
            set
            {
                this["G_FrameworkVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_is64Bit
        {
            get
            {
                return ((bool)(this["G_is64Bit"]));
            }
            set
            {
                this["G_is64Bit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool G_AtualizarAuto
        {
            get
            {
                return ((bool)(this["G_AtualizarAuto"]));
            }
            set
            {
                this["G_AtualizarAuto"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_PastaTemporaria
        {
            get
            {
                return ((string)(this["G_PastaTemporaria"]));
            }
            set
            {
                this["G_PastaTemporaria"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isLemon
        {
            get
            {
                return ((bool)(this["isLemon"]));
            }
            set
            {
                this["isLemon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int G_LastDigits
        {
            get
            {
                return ((int)(this["G_LastDigits"]));
            }
            set
            {
                this["G_LastDigits"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool runAsAdministrator
        {
            get
            {
                return ((bool)(this["runAsAdministrator"]));
            }
            set
            {
                this["runAsAdministrator"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Remessas\\")]
        public string G_RemessaFolder
        {
            get
            {
                return ((string)(this["G_RemessaFolder"]));
            }
            set
            {
                this["G_RemessaFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDados_Host
        {
            get
            {
                return ((string)(this["G_BancoDados_Host"]));
            }
            set
            {
                this["G_BancoDados_Host"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDados_Porta
        {
            get
            {
                return ((string)(this["G_BancoDados_Porta"]));
            }
            set
            {
                this["G_BancoDados_Porta"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDados_DataBase
        {
            get
            {
                return ((string)(this["G_BancoDados_DataBase"]));
            }
            set
            {
                this["G_BancoDados_DataBase"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDados_Usuario
        {
            get
            {
                return ((string)(this["G_BancoDados_Usuario"]));
            }
            set
            {
                this["G_BancoDados_Usuario"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_BancoDados_Senha
        {
            get
            {
                return ((string)(this["G_BancoDados_Senha"]));
            }
            set
            {
                this["G_BancoDados_Senha"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string G_SeparaConciliadoSN
        {
            get
            {
                return ((string)(this["G_SeparaConciliadoSN"]));
            }
            set
            {
                this["G_SeparaConciliadoSN"] = value;
            }
        }

    }
}
